version: '3'

services:

  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    container_name: node
    ports:
      - "3000:3000"
    networks:
      - nodenet
    volumes:
      - ./src:/usr/src/app
    tty: true

  db:
    image: mysql:8.0.25
    command: --innodb-use-native-aio=0
    container_name: mysql
    restart: always
    tty: true
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD= root
    networks:
      - nodenet

networks:
  nodenet:
    driver: bridge
