version: '3'

services:

  laravel:
    build:
      context: ./docker/laravel
      dockerfile: Dockerfile
    image: lucasxavier000/laravel
    container_name: laravel
    networks:
      - laranet

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    image: lucasxavier000/nginx
    container_name: nginx
    networks:
      - laranet
    ports:
      - "8080:80"

  db:
    image: mysql:8.0.25
    command: --innodb-use-native-aio=0
    container_name: mysql
    restart: always
    tty: true
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: appdb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - laranet

networks:
  laranet:
    driver: bridge
